language: node_js
node_js:
- 10.15.2
- 10.0.0
deploy:
  provider: npm
  email: dev@knowre.com
  api_key:
    secure: EiSww0i0a177DaF1NvdDlFdP/WkS2pnyMZdwU9hFn8hXyDiTGci1eAh6x1Td8XubvCUc2XSjZv+XzmCj6AAw6oOZ19B5wJ/X3Xr4n0Ch8ggsXrzQ1vL5bY77HlKkmzdVQVsYPckukNvoUTevNV/cYWNOwICeOZTTOfJhRHHwPL1bPZ9L+/JkFDhv/ZZRKpFVKrO2KEgDxf2NqaAhEe8IYKVX08T/cuL7Kox2tpAXtuPv1mFrlQWotI0Qf2mjxGCZwbpeq200zLV3WMidp00xIbDzsq7qqG3nvrjHTA7pabyncKZa000QN9fS7ppxMQCwRb7eE2D7xW7J9Fe0rixBWxZznx0v6Jz/Q0asXP9hhWfwxAd1B3eothiswxYd7pgXuZzA82DxH8TqVCHAGz3SMAvrYu/fNaokjN2Kk99GELk6mhju21PdMRu+ZHKdRmlJI/Nfx+ualL0lV+TNbrNLcX8j2JckSPA1AUiAtkTEwNyogBbJjehcSOssozg1psEIFnctYQagJexCchjjpRblCtvtsduGOJvXoV6ETDXWDHVIktyL7PDzrRyEvPlfme5Q7hS07dL+gKZ4qcvz6XItgY09fUOXl2sRBahdEOKoLoIfEK7qurUhy5B2ej+NsZECicBgHAjhHryQOtuSNC+SuhRHUPsWZqzCM3F1h3sIV4I=
  on:
    branch: stable
    node_js: 10.15.2
notifications:
  slack:
    secure: s9oTFET9F4FuTJm1c6Si4o/4t9ULV2/H/qwJbmjAYkx4LLbBQeJVG4mmAmitTJFYeTBCmvhc0yc8EKNFQPl+oCqk+2akVe1UL9lDAn6kNk57wle5VjttPReN/CPu8Q9RIWOlzuV40TpzZQdkBD3ffG98doLS8OoJQaIGUoxAO7Bqvs4dYB/NlMCsGUNGNQHUDignUMGehyzXXpx/z0apchidONRGqXDKbnMRSHyiao/X6L4t5Z9OrIntp9cpO7xv92aCt600ASxmDw7mtN7s6hB9tVztzHe3PC4atPtpvrUnguMOD4Vc6qquUdVm4gfWsAzG8VbywZMV8WdKoWd6EmYrfZiXqz91v6LxghpuEIbEeRP/u/52V8BO9Xz7m610YEDK04jdVSQ+naCogggYQ0nx6Ls9COOgygVtSbA0il2g75WkFPIsl46/dFfjikdT5PfC3uZX4GoZ0bjYoJyxYku7HucQsEWyQ0WJI11u+4ZN0fMi14BD5oOISHctl21pq5lz1qvpJkUigVlGf/pS9l1bYijQpm0PVdIZ5L7VF3JTeySp9IGOc69KcidwTxmcmGWyuPO/4S2kF67l/Nh2CGwJ6JozUXTssijkEb/UOf9RSIv4rLFyS8N3G9jbRmDOgrHFFFViUVrkXeey2d4tmW3C48047UIFlH63ry1FsI4=